# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoSwiftyCam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwiftyCam

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Performance'
pod 'Firebase/Invites'
pod 'Firebase/AdMob'
pod 'Firebase/Messaging'
pod 'FirebaseUI'
pod 'GoogleSignIn'
pod 'Firebase/Firestore'

end

target 'SwiftyCam-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyCam-iOS

pod 'SwiftyCam'

pod 'Firebase/Core'

end
